<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Summary</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>





<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<h1>Summary</h1>

<p>This report presents a statistical learning model based on Random Forests to predict the manner of execution of weight lifting exercises, using the dataset that was originally created by Velloso, E., Bulling, A., Gellersen, H., Ugulino, W. and Fuks, H. The base model that incorporates all variables is refined in subsequent steps to obtain a parsimonious model with seven predictors. The model&#39;s out of sample error rate is estimated at 0.18%.</p>

<h1>Introduction</h1>

<p>Wearable sensors were used to collect data on weight lifting exercises performed by 6 people. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. This study analyzes the data and builds a prediction model using statistical learning to classify the manner in which these people performed the exercise.</p>

<p>This report uses the Weight Lifting exercise Dataset prepared by <a href="http://groupware.les.inf.puc-rio.br/har">Velloso et al</a>.</p>

<p>The training data for this project are available here: 
[<a href="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv">https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv</a>]</p>

<p>The test data are available here: 
[<a href="https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv">https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv</a>]</p>

<h1>Exploratory Analysis</h1>

<p>Load the R packages used by this study.</p>

<pre><code class="r">library(knitr)
opts_knit$set(progress=TRUE, verbose=TRUE, self_contained=FALSE)
library(caret)
</code></pre>

<pre><code>## Loading required package: lattice
## Loading required package: ggplot2
</code></pre>

<pre><code class="r">library(randomForest)
library(ROCR)
</code></pre>

<p>We first perform a few basic format conversions to prepare the data for further analysis. The response variable is &quot;classe&quot;.</p>

<pre><code class="r"># Read data
# rm(list=ls())
training &lt;- read.csv(&quot;pml-training.csv&quot;, header=TRUE, colClasses=&quot;character&quot;)
predicting &lt;- read.csv(&quot;pml-testing.csv&quot;, header=TRUE, colClasses=&quot;character&quot;)

# Clean data
cleanData &lt;- function(x) {
    # convert categorical variables to factor and numeric variables to numeric
    # warnings may arise from invalid numeric values, eg #DIV/0! will be converted to NA
    x[, c(1, 2, 6, 160)] &lt;- lapply(x[, c(1, 2, 6, 160)], factor)
    x[, c(7:159)] &lt;- lapply(x[, c(7:159)], as.numeric)

    # convert dates
    x[, c(3:4)] &lt;- lapply(x[, c(3:4)], as.numeric)
    x$tsPosixct &lt;- lapply(x$raw_timestamp_part_1, as.POSIXct, origin = &quot;1970-01-01&quot;)
    x$tsDate &lt;- sapply(x$tsPosixct, format, &quot;%d/%m/%Y&quot;)
    x$tsTime &lt;- sapply(x$tsPosixct, format, &quot;%H:%M:%S&quot;)
    x[, c(&quot;tsDate&quot;, &quot;tsTime&quot;)] &lt;- lapply(x[, c(&quot;tsDate&quot;, &quot;tsTime&quot;)], factor)
    return(x)
}
training &lt;- cleanData(training)
predicting &lt;- cleanData(predicting)
print(dim(training))
</code></pre>

<pre><code>## [1] 19622   163
</code></pre>

<p>The raw data consists of 163 variables with 19622 data points. </p>

<pre><code class="r"># Exploratory analysis
# Analyze for missing values
colNA &lt;- sapply(training, function(x) sum(is.na(x)))
</code></pre>

<p>There are 63 variables without NA values. There are 100 variables with a total of 1925102 NA values. Below we investigate the variables with the highest number of missing values.</p>

<pre><code class="r">print(table(colNA[colNA &gt; 0]))
</code></pre>

<pre><code>## 
## 19216 19217 19218 19220 19221 19225 19226 19227 19248 19293 19294 19296 
##    67     1     1     1     4     1     4     2     2     1     1     2 
## 19299 19300 19301 19622 
##     1     4     2     6
</code></pre>

<pre><code class="r"># Many variables have 19216 NA rows, let&#39;s investigate
# Get the rows that have some value in them
training.na &lt;- training[!is.na(training$max_roll_belt),]
# Investigate the columns that have so many NA
training.na &lt;- cbind(training.na[,1:7], training.na[, colNA &gt; 0])
# print(summary(training.na))
print(colnames(training.na))
</code></pre>

<pre><code>##   [1] &quot;X&quot;                        &quot;user_name&quot;               
##   [3] &quot;raw_timestamp_part_1&quot;     &quot;raw_timestamp_part_2&quot;    
##   [5] &quot;cvtd_timestamp&quot;           &quot;new_window&quot;              
##   [7] &quot;num_window&quot;               &quot;kurtosis_roll_belt&quot;      
##   [9] &quot;kurtosis_picth_belt&quot;      &quot;kurtosis_yaw_belt&quot;       
##  [11] &quot;skewness_roll_belt&quot;       &quot;skewness_roll_belt.1&quot;    
##  [13] &quot;skewness_yaw_belt&quot;        &quot;max_roll_belt&quot;           
##  [15] &quot;max_picth_belt&quot;           &quot;max_yaw_belt&quot;            
##  [17] &quot;min_roll_belt&quot;            &quot;min_pitch_belt&quot;          
##  [19] &quot;min_yaw_belt&quot;             &quot;amplitude_roll_belt&quot;     
##  [21] &quot;amplitude_pitch_belt&quot;     &quot;amplitude_yaw_belt&quot;      
##  [23] &quot;var_total_accel_belt&quot;     &quot;avg_roll_belt&quot;           
##  [25] &quot;stddev_roll_belt&quot;         &quot;var_roll_belt&quot;           
##  [27] &quot;avg_pitch_belt&quot;           &quot;stddev_pitch_belt&quot;       
##  [29] &quot;var_pitch_belt&quot;           &quot;avg_yaw_belt&quot;            
##  [31] &quot;stddev_yaw_belt&quot;          &quot;var_yaw_belt&quot;            
##  [33] &quot;var_accel_arm&quot;            &quot;avg_roll_arm&quot;            
##  [35] &quot;stddev_roll_arm&quot;          &quot;var_roll_arm&quot;            
##  [37] &quot;avg_pitch_arm&quot;            &quot;stddev_pitch_arm&quot;        
##  [39] &quot;var_pitch_arm&quot;            &quot;avg_yaw_arm&quot;             
##  [41] &quot;stddev_yaw_arm&quot;           &quot;var_yaw_arm&quot;             
##  [43] &quot;kurtosis_roll_arm&quot;        &quot;kurtosis_picth_arm&quot;      
##  [45] &quot;kurtosis_yaw_arm&quot;         &quot;skewness_roll_arm&quot;       
##  [47] &quot;skewness_pitch_arm&quot;       &quot;skewness_yaw_arm&quot;        
##  [49] &quot;max_roll_arm&quot;             &quot;max_picth_arm&quot;           
##  [51] &quot;max_yaw_arm&quot;              &quot;min_roll_arm&quot;            
##  [53] &quot;min_pitch_arm&quot;            &quot;min_yaw_arm&quot;             
##  [55] &quot;amplitude_roll_arm&quot;       &quot;amplitude_pitch_arm&quot;     
##  [57] &quot;amplitude_yaw_arm&quot;        &quot;kurtosis_roll_dumbbell&quot;  
##  [59] &quot;kurtosis_picth_dumbbell&quot;  &quot;kurtosis_yaw_dumbbell&quot;   
##  [61] &quot;skewness_roll_dumbbell&quot;   &quot;skewness_pitch_dumbbell&quot; 
##  [63] &quot;skewness_yaw_dumbbell&quot;    &quot;max_roll_dumbbell&quot;       
##  [65] &quot;max_picth_dumbbell&quot;       &quot;max_yaw_dumbbell&quot;        
##  [67] &quot;min_roll_dumbbell&quot;        &quot;min_pitch_dumbbell&quot;      
##  [69] &quot;min_yaw_dumbbell&quot;         &quot;amplitude_roll_dumbbell&quot; 
##  [71] &quot;amplitude_pitch_dumbbell&quot; &quot;amplitude_yaw_dumbbell&quot;  
##  [73] &quot;var_accel_dumbbell&quot;       &quot;avg_roll_dumbbell&quot;       
##  [75] &quot;stddev_roll_dumbbell&quot;     &quot;var_roll_dumbbell&quot;       
##  [77] &quot;avg_pitch_dumbbell&quot;       &quot;stddev_pitch_dumbbell&quot;   
##  [79] &quot;var_pitch_dumbbell&quot;       &quot;avg_yaw_dumbbell&quot;        
##  [81] &quot;stddev_yaw_dumbbell&quot;      &quot;var_yaw_dumbbell&quot;        
##  [83] &quot;kurtosis_roll_forearm&quot;    &quot;kurtosis_picth_forearm&quot;  
##  [85] &quot;kurtosis_yaw_forearm&quot;     &quot;skewness_roll_forearm&quot;   
##  [87] &quot;skewness_pitch_forearm&quot;   &quot;skewness_yaw_forearm&quot;    
##  [89] &quot;max_roll_forearm&quot;         &quot;max_picth_forearm&quot;       
##  [91] &quot;max_yaw_forearm&quot;          &quot;min_roll_forearm&quot;        
##  [93] &quot;min_pitch_forearm&quot;        &quot;min_yaw_forearm&quot;         
##  [95] &quot;amplitude_roll_forearm&quot;   &quot;amplitude_pitch_forearm&quot; 
##  [97] &quot;amplitude_yaw_forearm&quot;    &quot;var_accel_forearm&quot;       
##  [99] &quot;avg_roll_forearm&quot;         &quot;stddev_roll_forearm&quot;     
## [101] &quot;var_roll_forearm&quot;         &quot;avg_pitch_forearm&quot;       
## [103] &quot;stddev_pitch_forearm&quot;     &quot;var_pitch_forearm&quot;       
## [105] &quot;avg_yaw_forearm&quot;          &quot;stddev_yaw_forearm&quot;      
## [107] &quot;var_yaw_forearm&quot;
</code></pre>

<pre><code class="r">print(dim(training.na))
</code></pre>

<pre><code>## [1] 406 107
</code></pre>

<p>406 rows apparently contain a summary of exercises performed previously, providing min, max, stddev, mean, and var metrics. It is decided to remove these rows, by selecting new_window != yes.</p>

<p>Also all variables with missing values are removed, as imputing would be impractical given the large number of missing values (19216 or more of a total of 19622 data rows).</p>

<pre><code class="r">training &lt;- training[training$new_window != &quot;yes&quot;,]
training &lt;- training[, colNA == 0]
print(dim(training))
</code></pre>

<pre><code>## [1] 19216    63
</code></pre>

<p>After removing variables with missing values there are 63 variables remaining with 0 missing values.</p>

<h1>Prediction Study Design</h1>

<p>Before we start building the model we remove a few more variables such as the raw timestamps. Also the time variable is removed.</p>

<pre><code class="r"># Columns to exclude from model
colToExclude &lt;- c(&quot;X&quot;, &quot;raw_timestamp_part_1&quot;, &quot;raw_timestamp_part_2&quot;, &quot;cvtd_timestamp&quot;, &quot;tsPosixct&quot;)
# Exclude tsTime as well, because rf can&#39;t handle predictors with more than 53 categories
colToExclude &lt;- c(colToExclude, &quot;tsTime&quot;)
idxToExclude &lt;- which(colnames(training) %in% colToExclude)
training &lt;- training[,-idxToExclude]
</code></pre>

<p>Next we split the data set in a training set (80%) and a test set (20%). The response variable classe has five classes. A random selection is made within each class separately using the function createDataPartition (caret).</p>

<pre><code class="r"># Data preparation
print(table(training$classe))
</code></pre>

<pre><code>## 
##    A    B    C    D    E 
## 5471 3718 3352 3147 3528
</code></pre>

<pre><code class="r">set.seed(111)
# split data in 80% training, 20% testing
# caret createDataPartition makes random selection within each class 
# library(caret)
ind &lt;- createDataPartition(y=training$classe, p=0.8, list=FALSE)
trn &lt;- training[ind,]; tst &lt;- training[-ind,]
print(table(trn$classe)); print(table(tst$classe))
</code></pre>

<pre><code>## 
##    A    B    C    D    E 
## 4377 2975 2682 2518 2823
</code></pre>

<pre><code>## 
##    A    B    C    D    E 
## 1094  743  670  629  705
</code></pre>

<h1>Model Construction</h1>

<p>The model will be built using a Random Forests approach. Random Forests is a modelling method that is particularly suited for multi-value classification models. It grows decision trees on different parts of the training set and averages the fitted trees to obtain a tree that has low bias and reduced variance. Unlike bootstrap aggregating (bagging) Random Forests selects from a subset of variables at each candidate split (tree node) in the learning process. Cross validation is performed by the Random Forests algorithm itself, using the Out Of Bag or out of sample error as the estimate how well the model will perform on the unseen test data. </p>

<p>This study does not investigate the applicability of other modelling methods for the weight lifting exercise data set at hand. </p>

<p>The following steps are taken to build the final model:</p>

<ul>
<li>Fit a Random Forests model on the training set, and use the mtry parameter to find an optimal setting for m, the number of randomly selected variables that is considered for a new node split.</li>
<li>Using the model obtained with the optimal setting for m, create refined models by selecting variables based on their importance in the first model. Model refinement is done using two mtry settings: 3, and the default setting square root of p, the number of variables.</li>
<li>Select the model that performs best, according to the Out Of Bag error rate.</li>
</ul>

<pre><code class="r"># Function to calculate Out Of Bag error rate
# library(randomForest)
oobError &lt;- function(model.rf) {
    # get confusion matrix
    cm &lt;- model.rf$confusion[,1:length(model.rf$classes)]
    # out of bag estimate of error rate
    return((sum(cm) - sum(diag(cm))) / sum(cm))
}
</code></pre>

<h2>Initial Model</h2>

<p>First we obtain the best value of m, the number of randomly selected variables to consider for each new tree node. We analyze with all variables (bagging), half of the variables, a range between 6 and 12, and 3.</p>

<pre><code class="r"># Exclude total_ variables
trnCols &lt;- !grepl(&quot;^total_&quot;, colnames(trn))
# Fit models
modelComparison &lt;- data.frame(mtry=0, oobError=0)
models &lt;- lapply(c(ncol(trn[,trnCols])-1, 26, 12:6, 3), function(m) {
    set.seed(1111)
    nt &lt;- 100
    # print(paste(&quot;mtry =&quot;, m, &quot;ntree =&quot;, nt))
    fit.rf &lt;- randomForest(classe ~ ., data=trn[,trnCols], mtry=m, ntree=nt, importance=TRUE)
    model &lt;- list(mtry = m, fit.rf = fit.rf, oobErr = oobError(fit.rf))
})
modelComparison &lt;- matrix(data=c(sapply(models, &quot;[&quot;, 1), sapply(models, &quot;[&quot;, 3)), byrow = FALSE, ncol=2)
colnames(modelComparison) &lt;- c(&quot;mtry&quot;, &quot;oobErr&quot;)

# Find model with best oobError and lowest mtry
print(modelComparison)
</code></pre>

<pre><code>##       mtry oobErr     
##  [1,] 52   0.005788618
##  [2,] 26   0.002406504
##  [3,] 12   0.001691057
##  [4,] 11   0.001886179
##  [5,] 10   0.002406504
##  [6,] 9    0.002471545
##  [7,] 8    0.002601626
##  [8,] 7    0.002211382
##  [9,] 6    0.003186992
## [10,] 3    0.003577236
</code></pre>

<pre><code class="r">print(which.min(modelComparison[,2]))
</code></pre>

<pre><code>## [1] 3
</code></pre>

<pre><code class="r"># Continue with this model
m &lt;- which.min(modelComparison[,2])
mtry &lt;- models[[m]]$mtry
imp &lt;- as.data.frame(importance(models[[m]]$fit.rf)[,c(&quot;MeanDecreaseAccuracy&quot;,&quot;MeanDecreaseGini&quot;)])
</code></pre>

<p>A value of 12 appears to give an optimal result. The figure below shows the relative importance of the variables used in the model. The long tails have little separation between the individual values. It suggests that the model can be simplified considerably without making too big a concession to the model&#39;s expected performance.</p>

<pre><code class="r"># Variable importance plot
# library(randomForest)
randomForest::varImpPlot(models[[m]]$fit.rf, main = &quot;Variable Importance&quot;, 
                         col=&quot;blue&quot;, cex=0.8)
</code></pre>

<p><img src="figure/diagnostic_model1-1.png" alt="plot of chunk diagnostic_model1"> </p>

<h2>Model Refinement</h2>

<p>To make the model more parsimonious while keeping prediction accuracy acceptable we remove variables with the lowest Mean Decrease Accuracy and Mean Decrease Gini values. These diagnostics indicate the extent to which the variables have an improving effect on the model&#39;s prediction performance and classification of the data. The Gini coefficient is a measure for the homogeneity (purity) of the nodes and leaves in the forest.</p>

<pre><code class="r">print(summary(imp$MeanDecreaseAccuracy))
</code></pre>

<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   9.868  11.910  13.000  14.400  30.220
</code></pre>

<pre><code class="r">print(summary(imp$MeanDecreaseGini))
</code></pre>

<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0    67.7   143.3   233.7   241.9  1439.0
</code></pre>

<p>The figure below shows that the variables in the upper right corner might be the most important ones for the final model.</p>

<pre><code class="r">with(imp, plot(MeanDecreaseAccuracy, MeanDecreaseGini, main=&quot;Variable Importance&quot;, pch=19, col=&quot;blue&quot;))
impPlotData &lt;- imp[imp$MeanDecreaseAccuracy &gt; 15 | imp$MeanDecreaseGini &gt; 300,]
with(impPlotData, text(MeanDecreaseAccuracy, MeanDecreaseGini, 
                       labels = rownames(impPlotData), cex = 0.6, pos = 2))
</code></pre>

<p><img src="figure/diagnostic_model3-1.png" alt="plot of chunk diagnostic_model3"> </p>

<p>Before we draw this conclusion we generate different models based on different sets of variables. Starting with the full list of variables, with each step we remove an increasing number of the lesser important variables.</p>

<pre><code class="r"># Stepwise remove variables to obtain a parsimonious model with acceptable accuracy
# Candidates for removal are variables with lowest MDA and MDG

# Data variable selection
# Baseline model includes all variables (p), the others drop variables of lowest importance 
rmVars &lt;- list(
    c(&quot;&quot;),
    rownames(imp[imp$MeanDecreaseAccuracy &lt; 10 &amp; imp$MeanDecreaseGini &lt; 75,]),
    rownames(imp[imp$MeanDecreaseAccuracy &lt; 13 &amp; imp$MeanDecreaseGini &lt; 145,]),
    rownames(imp[imp$MeanDecreaseAccuracy &lt; 14 &amp; imp$MeanDecreaseGini &lt; 145,]),
    rownames(imp[imp$MeanDecreaseAccuracy &lt; 14 &amp; imp$MeanDecreaseGini &lt; 200,]),
    rownames(imp[imp$MeanDecreaseAccuracy &lt; 14 &amp; imp$MeanDecreaseGini &lt; 235,]),
    rownames(imp[imp$MeanDecreaseAccuracy &lt; 14 &amp; imp$MeanDecreaseGini &lt; 250,]),
    rownames(imp[imp$MeanDecreaseAccuracy &lt; 20 &amp; imp$MeanDecreaseGini &lt; 250,]),
    rownames(imp[imp$MeanDecreaseAccuracy &lt; 20 &amp; imp$MeanDecreaseGini &lt; 500,]),
    rownames(imp[imp$MeanDecreaseAccuracy &lt; 22 &amp; imp$MeanDecreaseGini &lt; 500,]),
    rownames(imp[imp$MeanDecreaseAccuracy &lt; 22 &amp; imp$MeanDecreaseGini &lt; 650,])
)
</code></pre>

<p>For each subset of variables the model is generated with mtry set to 3 and with the default setting of mtry, the square root of the number of variables.</p>

<p>We compare the resulting models and select the one with the lowest Out Of Bag error rate. </p>

<pre><code class="r"># Fit models
# Iterate in reverse order, starting with minimum nr of variables
models2 &lt;- lapply(c(3, 0), function(mtry) {
    models2 &lt;- lapply(rev(rmVars), function(v) {
        nt &lt;- 100
        trn2 &lt;- trn[,!colnames(trn[,trnCols]) %in% v]
        # print(paste(&quot;mtry =&quot;, mtry, &quot;ntree =&quot;, nt, &quot;variables =&quot;, ncol(trn2)-1))
        set.seed(1111)
        if (mtry &gt; 0) {
            # specific value for mtry
            fit.rf &lt;- randomForest(classe ~ ., data=trn2, mtry=mtry, ntree=nt, importance=TRUE)
        }
        else {
            # default value for mtry: sqrt(p) 
            fit.rf &lt;- randomForest(classe ~ ., data=trn2, ntree=nt, importance=TRUE)        
        }            
        model &lt;- list(mtry = fit.rf$mtry, fit.rf = fit.rf, oobErr = oobError(fit.rf), 
                      nVars = ncol(trn2)-1, vars = setdiff(colnames(trn2), &quot;classe&quot;), rmVars = v)
    })
})
models2 &lt;- c(models2[[1]], models2[[2]])
modelComparison2 &lt;- matrix(data=c(sapply(models2, &quot;[&quot;, 1), 
                                  sapply(models2, &quot;[&quot;, 3),
                                  sapply(models2, &quot;[&quot;, 4)), 
                           byrow = FALSE, ncol=3)
colnames(modelComparison2) &lt;- c(&quot;mtry&quot;, &quot;oobErr&quot;, &quot;nVars&quot;)

# Find model with best oobError and lowest nr of variables 
print(modelComparison2)
</code></pre>

<pre><code>##       mtry oobErr       nVars
##  [1,] 3    0.0009105691 7    
##  [2,] 3    0.00104065   9    
##  [3,] 3    0.00104065   9    
##  [4,] 3    0.002276423  15   
##  [5,] 3    0.003642276  23   
##  [6,] 3    0.003642276  24   
##  [7,] 3    0.003642276  26   
##  [8,] 3    0.00403252   31   
##  [9,] 3    0.00403252   33   
## [10,] 3    0.004292683  49   
## [11,] 3    0.003707317  56   
## [12,] 2    0.001430894  7    
## [13,] 3    0.00104065   9    
## [14,] 3    0.00104065   9    
## [15,] 3    0.002276423  15   
## [16,] 4    0.00195122   23   
## [17,] 4    0.002081301  24   
## [18,] 5    0.002536585  26   
## [19,] 5    0.002731707  31   
## [20,] 5    0.003056911  33   
## [21,] 7    0.002666667  49   
## [22,] 7    0.002601626  56
</code></pre>

<pre><code class="r">print(which.min(modelComparison2[,2]))
</code></pre>

<pre><code>## [1] 1
</code></pre>

<pre><code class="r"># Continue with this final model
m &lt;- which.min(modelComparison2[,2])
final &lt;- models2[[m]]$fit.rf
finalCols &lt;- models2[[m]]$vars
</code></pre>

<p>The final model uses 7 variables.</p>

<pre><code class="r"># Final model and some diagnostics
print(final)
</code></pre>

<pre><code>## 
## Call:
##  randomForest(formula = classe ~ ., data = trn2, mtry = mtry,      ntree = nt, importance = TRUE) 
##                Type of random forest: classification
##                      Number of trees: 100
## No. of variables tried at each split: 3
## 
##         OOB estimate of  error rate: 0.09%
## Confusion matrix:
##      A    B    C    D    E  class.error
## A 4377    0    0    0    0 0.0000000000
## B    0 2973    1    0    1 0.0006722689
## C    0    3 2678    1    0 0.0014914243
## D    0    0    1 2516    1 0.0007942812
## E    1    2    0    3 2817 0.0021253985
</code></pre>

<pre><code class="r"># Usage frequency of variables
# library(randomForest)
print(randomForest::varUsed(final, by.tree=FALSE, count=TRUE))
</code></pre>

<pre><code>## [1] 11009  4910  6049  4514  4530  4091   339
</code></pre>

<pre><code class="r"># Importance
print(randomForest::importance(final))
</code></pre>

<pre><code>##                          A        B        C        D        E
## num_window        61.38658 60.45295 81.78776 55.74778 30.86072
## roll_belt         24.23348 41.93334 32.56933 39.74925 34.84604
## yaw_belt          23.54533 40.90853 34.79908 36.64446 16.86775
## accel_dumbbell_z  26.57164 27.84391 25.40782 30.42741 29.12394
## magnet_dumbbell_y 25.41971 31.16803 41.11992 35.86792 24.94813
## accel_forearm_z   14.49214 17.04572 17.51552 17.71407 18.17184
## tsDate            10.13436 12.83160 11.38402 10.93579 10.72579
##                   MeanDecreaseAccuracy MeanDecreaseGini
## num_window                    83.95659        4832.5973
## roll_belt                     48.15301        2160.8678
## yaw_belt                      42.76166        1762.1695
## accel_dumbbell_z              33.11120        1250.3234
## magnet_dumbbell_y             35.39380        1424.9423
## accel_forearm_z               23.46304         496.0946
## tsDate                        13.36371         227.2153
</code></pre>

<pre><code class="r"># Importance plot
# library(randomForest)
randomForest::varImpPlot(final, n.var = models2[[m]]$nVars, main=&quot;Variable Importance&quot;, 
                         pch=19, col=&quot;blue&quot;, cex=0.8)
</code></pre>

<p><img src="figure/diagnostic_model5-1.png" alt="plot of chunk diagnostic_model5"> </p>

<p>The plot of variable importance shows that the seven remaining variables in the model are all having a significant influence on the accuracy of the classification and on the purity of the nodes and leaves. The long tail of variables with similar importance scores has disappeared. In the next section we will analyze the expected classification performance of the new model.</p>

<h2>Expected Performance</h2>

<p>To assess the expected prediction performance on the test set we look at the plots of the margins of prediction and the ROC curve of the trained model.</p>

<p>The margin of a data point is the proportion of votes for the correct class minus the maximum proportion of votes for the other classes. If the margin is positive it means the data point is correctly classified. One means perfect classification, zero means that the model does not clearly classify, whereas minus one would mean a fully imperfect classification.</p>

<p>The histogram shows that the vast majority of data points are perfectly classified.</p>

<pre><code class="r"># Margins of prediction
# library(randomForest)
hist(randomForest::margin(final), col=&quot;blue&quot;, main=&quot;Histogram of prediction margin&quot;, xlab=&quot;Prediction margin&quot;)
</code></pre>

<p><img src="figure/diagnostic_model6-1.png" alt="plot of chunk diagnostic_model6"> </p>

<p>The ROC (receiver operating characteristics) curve is a graphical plot that depicts the performance of a binary classification model. It compares the true positive rate (vertical axis) and the false positive rate (horizontal axis). </p>

<p>Because our model uses five classes, we show a curve for each class to assess the classification performance for each outcome (A/Not A, B/Not B, etc.).</p>

<p>The curves show that the model is performing very well for all outcomes.</p>

<pre><code class="r"># ROC plot using ROCR library
# Show a ROC curve for each class prediction.
# Note: ROCR supports two-valued classification only (true/false, A/not A, etc).
# library(ROCR)
votes &lt;- as.data.frame(final$votes)
op &lt;- par(mfrow=c(2,3))
for (className in levels(trn$classe)) {
    # message(className)
    predictions &lt;- as.numeric(votes[,className])
    correctClass &lt;- grepl(className, trn$classe)
    pred &lt;- ROCR::prediction(predictions, labels=correctClass)
    # Area under curve
    perfAuc &lt;- ROCR::performance(pred, &quot;auc&quot;)
    auc &lt;- perfAuc@y.values[[1]]
    # ROC curve
    perfRoc &lt;- ROCR::performance(pred,&quot;tpr&quot;,&quot;fpr&quot;)
    ROCR::plot(perfRoc, main=paste(&quot;ROC plot&quot;, &quot;classe =&quot;, className), col=&quot;blue&quot;)
    text(0.5, 0.5, paste(&quot;AUC =&quot;, format(auc, digits=5, scientific=FALSE)))
}
par(op)
</code></pre>

<p><img src="figure/diagnostic_model7-1.png" alt="plot of chunk diagnostic_model7"> </p>

<h1>Model Validation</h1>

<p>We now validate the model against the test set.</p>

<pre><code class="r"># Validate using test set
pred.rf &lt;- predict(final, newdata=tst[,finalCols], type=&quot;response&quot;)
pred.table &lt;- table(observed = tst$classe, predicted = pred.rf)
print(pred.table)
</code></pre>

<pre><code>##         predicted
## observed    A    B    C    D    E
##        A 1094    0    0    0    0
##        B    1  742    0    0    0
##        C    0    3  667    0    0
##        D    0    0    0  629    0
##        E    0    2    0    1  702
</code></pre>

<pre><code class="r">print((sum(pred.table) - sum(diag(pred.table))) / sum(pred.table))
</code></pre>

<pre><code>## [1] 0.001822442
</code></pre>

<p>The out of sample error rate in a classification model is calculated as the ratio of misclassifications. The out of sample error of our 7-variable Random Forests model is 0.18%. We therefore accept this model as the final one to use for classifying the prediction set.</p>

<h1>Prediction</h1>

<p>We now predict the classes of the 20 observations in the pml-testing.csv dataset.</p>

<pre><code class="r"># Predict answers
answers &lt;- predict(final, newdata=predicting[,finalCols])
print(answers)
</code></pre>

<pre><code>##  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 
##  B  A  B  A  A  E  D  B  A  A  B  C  B  A  E  E  A  B  B  B 
## Levels: A B C D E
</code></pre>

<p>Output the result to separate files using the code suggested in the assignment.</p>

<pre><code class="r"># Export answers to separate text files using Coursera script
pml_write_files = function(x){
    n = length(x)
    for(i in 1:n){
        filename = paste0(&quot;problem_id_&quot;,i,&quot;.txt&quot;)
        write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
    }
}
pml_write_files(answers)
</code></pre>

<h1>References</h1>

<p>Velloso, E.; Bulling, A.; Gellersen, H.; Ugulino, W.; Fuks, H. <a href="http://groupware.les.inf.puc-rio.br/work.jsf?p1=11201%5D">Qualitative Activity Recognition of Weight Lifting Exercises</a>. Proceedings of 4th International Conference in Cooperation with SIGCHI (Augmented Human &#39;13) . Stuttgart, Germany: ACM SIGCHI, 2013. </p>

</body>

</html>
